title: Stochastic Entity
description: Ramblings about statistics, python and collapsed stochastic brainstates!
author: Vikrant Kamble
github: https://github.com/vikrantkamble
about: I'm an astronomer aspiring to be a data scientist/programmer
disqus_shortname: vkamble
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/20160716_183931.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/vikrant10622"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/vikrant-a-kamble/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/VikrantKamble"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://vikrantkamble.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: vkamble
